# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
hooks = [
  {
    id = "commitizen",
    stages = ["commit-msg"]
  },
  {
    id = "commitizen-branch",
    stages = ["pre-push"]
  }
]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "v4.16.3"

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-builtin-literals" },
  { id = "check-docstring-first" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.16"
hooks = [
  {
    id = "ruff",
    args = ["--fix"]
  },
  { id = "ruff-format" }
]

[[repos]]
repo = "https://github.com/gitleaks/gitleaks"
rev = "v8.30.0"
hooks = [
  { id = "gitleaks" }
]
