[project]
name = "resumegen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "dev-in-f" }]
requires-python = ">=3.13"
dependencies = [
    "jinja2",
    "pikepdf",
    "pydantic",
    "pyyaml",
    "weasyprint",
]

[project.scripts]
resumegen = "resumegen:main"

[build-system]
requires = ["uv_build>=0.10.2,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["commitizen", "pre-commit", "pytest", "pytest-cov"]

[tool.ruff.lint]
select = ["E", "F", "B", "UP", "SIM", "I"]
unfixable = ["B"]

[tool.bandit.assert_used]
skips = ["*_test.py", "*test_*.py"]


[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version_provider = "uv"
major_version_zero = true
