---
# yaml-language-server: $schema=./appconfig-schema.json
logging_config:
  level: INFO
  file: app.log
data_file: resume.example.yaml
output_config:
  output_dir: output
  output_filename: "{author}_resume_{date}.pdf"
  overwrite: false
template_dir: templates
