---
# yaml-language-server: $schema=../schemas/config-schema.json
log_level: INFO
log_file: app.log
output_dir: output
output_filename: "{author}_resume_{date}.pdf"
overwrite_existing: false
template_dir: templates
