# Default configuration
# yaml-language-server: $schema: ../src/resumegen/schemas/config.json
---
# The directory to output generated files
output_dir: output
# A template for the output filename. The following placeholders are available:
# author, title, date, language, description, keywords (From DocumentMetadata).
output_filename: "{author}_resume_{date}.pdf"
# Whether to overwrite existing files in the output directory.
overwrite_existing: false
# The directory containing the templates to use for generating resumes.
template_dir: templates
# The filename of the template to use for generating resumes.
template_name: template.html.j2
